# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8f62bfe67d10343cb1252ae35f01b7fc3d6029ad1fb1d32fc4d7af40cde3f064e51c988245995668af7045fe2e98fc17e9a4910e4f6fc40484da71b233ac73d

test:
  secret_key_base: a0d0874885f884251f2406b07b563e264ebabe7b0c5cfbe99cbdbb3f9bcca3af999c68ca2af05cb79ecccd8945f6dfe174f05c07f9b53892c10191f17edc08ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
